# Generated by Django 3.2.13 on 2022-10-15 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20221015_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='댓글')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='갱신일')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.article', verbose_name='게시글')),
            ],
        ),
    ]
